### ISSUE TITLE
FnCreateDevice takes Option<PhysicalDevice>?

### ISSUE THREAD

**Issue by ishitatsuyuki** [sjb3d/spark#3]
`FnCreateDevice` takes an optional PhysicalDevice parameter:

https://github.com/sjb3d/spark/blob/master/spark/src/vk.rs#L43582-L43587

but this parameter is clearly specified to be valid in the [spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateDevice.html#VUID-vkCreateDevice-physicalDevice-parameter).

Some other example like `FnCreateSwapchainKHR` also seems to have the same issue.

**Comment by simonb-unity** [comment]
That is true, but I'd expect a user of the library to use one of the Device/Instance wrapper functions rather than the function pointer directly!  The wrapper functions do expose the parameter as non-optional:

```
    pub unsafe fn create_device(
        &self,
        physical_device: vk::PhysicalDevice,
        p_create_info: &vk::DeviceCreateInfo,
        p_allocator: Option<&vk::AllocationCallbacks>,
        version: vk::Version,
    ) -> result::Result<Device, LoaderError> {
```

Do you have a use case for using the function pointers directly where this important?  I'm hesitant to change this behaviour since I was regarding the function pointers as an implementation detail.

**Comment by sjb3d** [comment]
That is true, but I'd expect a user of the library to use one of the Device/Instance wrapper functions rather than the function pointer directly! The wrapper functions do expose the parameter as non-optional:

```
    pub unsafe fn create_device(
        &self,
        physical_device: vk::PhysicalDevice,
        p_create_info: &vk::DeviceCreateInfo,
        p_allocator: Option<&vk::AllocationCallbacks>,
        version: vk::Version,
    ) -> result::Result<Device, LoaderError> {
```

Do you have a use case for using the function pointers directly where this important? I'm hesitant to change this behaviour since I was regarding the function pointers as an implementation detail.

**Comment by ishitatsuyuki** [comment]
My use case is rather peculiar: developing a Vulkan layer.

A layer intercepts calls to functions including vkCreateDevice. For correctness I ensure their signature matches the function pointer definition by casting (e.g. `my_create_device as FnCreateDevice`).

**Comment by sjb3d** [comment]
Ah ok!

On reflection, I am still not sure if I should push this kind of spec detail into the function pointer types.  For example, for your use case, Vulkan applications written in other languages may call into your layer with a null handle even though the spec requires a non-null one, so I think the function pointer **has** to use types that cover all possible inputs, not only ones that are expected?

For the same reason, the callbacks use pointers (which can be null) with the wrappers making use of references (which cannot).

**Comment by ishitatsuyuki** [comment]
> Vulkan applications written in other languages may call into your layer with a null handle even though the spec requires a non-null one

It's certainly possible for apps to violate the contract, although that's no different from other contract violation like passing freed or invalid pointers. The Vulkan spec allows undefined behavior if the VUIDs are violated.

That said, you're right that encoding API contracts into function pointers isn't a good idea. Function pointers are just a translation of the C API declarations and nothing more. Something like a validation layer might also want to receive function calls with violations without incurring UB immediately.

I'll close this for now.
